# Generated by Django 4.2.3 on 2025-04-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('template_pdf', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_locador', models.CharField(max_length=100)),
                ('nacionalidade_locador', models.CharField(default='brasileira', max_length=50)),
                ('estado_civil_locador', models.CharField(default='casada', max_length=50)),
                ('profissao_locador', models.CharField(default='aposentada', max_length=50)),
                ('rg_locador', models.CharField(max_length=20)),
                ('cpf_locador', models.CharField(max_length=14)),
                ('endereco_locador', models.CharField(default='nesta cidade', max_length=200)),
                ('nome_locatario', models.CharField(max_length=100)),
                ('nacionalidade_locatario', models.CharField(default='brasileiro', max_length=50)),
                ('rg_locatario', models.CharField(max_length=20)),
                ('cpf_locatario', models.CharField(max_length=14)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=50)),
                ('quadra', models.CharField(blank=True, max_length=50)),
                ('casa', models.CharField(blank=True, max_length=50)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(default='RJ', max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_aluguel_extenso', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('dia_pagamento', models.IntegerField()),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_locacao', to='contratos_app.contrato')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos_app.tipocontrato'),
        ),
    ]
